### ISSUE TITLE
Not working BMCS 2023.6.1 on 1.20.1

### ISSUE THREAD

**Issue by VBro170** [syorito-hatsuki/bluemap-custom-skin-server#5]
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bluemap_custom_skin_server'!

at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]

at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]

at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]

Caused by: java.lang.NoClassDefFoundError: dev/syoritohatsuki/duckyupdater/DuckyUpdater

at dev.syoritohatsuki.bluemapcustomskinserver.BlueMapCustomSkinServerAddon.onInitialize(BlueMapCustomSkinServerAddon.kt:22) ~[bluemap-custom-skin-server-2023.6.1.jar:?]

at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]

... 7 more

Caused by: java.lang.ClassNotFoundException: dev.syoritohatsuki.duckyupdater.DuckyUpdater

at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]

at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]

at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]

at dev.syoritohatsuki.bluemapcustomskinserver.BlueMapCustomSkinServerAddon.onInitialize(BlueMapCustomSkinServerAddon.kt:22) ~[bluemap-custom-skin-server-2023.6.1.jar:?]

at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]

... 7 more`

Fabric api - 0.85.0
Kotlin - 1.10.8-1.9.0
BlueMap - 3.16

**Comment by syorito-hatsuki** [comment]
https://modrinth.com/mod/bcss/version/2023.8.1
