### ISSUE TITLE
last version don't work, server error on starting

### ISSUE THREAD

**Issue by mindryder** [syorito-hatsuki/bluemap-custom-skin-server#6]
[22:56:49] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bluemap_custom_skin_server'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchFieldError: INSTANCE
	at dev.syoritohatsuki.bluemapcustomskinserver.BlueMapCustomSkinServerAddon.onInitialize(BlueMapCustomSkinServerAddon.kt:22) ~[bluemap-custom-skin-server-2023.8.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 8 more

**Comment by syorito-hatsuki** [comment]
Minecraft Version?
Fabric API?

**Comment by mindryder** [comment]
1.20.1 | fabric-api-0.88.1+1.20.1

**Comment by syorito-hatsuki** [comment]
Looks like that works fine. Try to download from [Modrinth](https://modrinth.com/mod/bcss/version/2023.8.1) and  give more info if still does not work

![image](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/33298273/983d1007-8927-4bb3-b264-87b994416585)
![image](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/assets/33298273/d2b0f434-e965-49a0-84d5-0a10526def72)

**Comment by mindryder** [comment]
[00:33:24] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bluemap_custom_skin_server'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
Caused by: java.lang.NoSuchFieldError: INSTANCE
        at dev.syoritohatsuki.bluemapcustomskinserver.BlueMapCustomSkinServerAddon.onInitialize(BlueMapCustomSkinServerAddon.kt:22) ~[bluemap-custom-skin-server-2023.8.1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more

**Comment by mindryder** [comment]
[latest.log](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/files/12602201/latest.log)

**Comment by syorito-hatsuki** [comment]
> [latest.log](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/files/12602201/latest.log)
> 

Where did u download it?

**Comment by mindryder** [comment]
> > [latest.log](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/files/12602201/latest.log)
> 
> Where did u download it?

Modrinth

**Comment by syorito-hatsuki** [comment]
> > > [latest.log](https://github.com/syorito-hatsuki/bluemap-custom-skin-server/files/12602201/latest.log)
> > 
> > 
> > Where did u download it?
> 
> Modrinth

Can u send me to [mail](mailto:enderdron3@gmail.com) mods folder so I can make some test with u pack

**Comment by mindryder** [comment]
Sended

**Comment by syorito-hatsuki** [comment]
Remove `ducky-updater-lib-2023.6.1.jar`. You should not download it. It is embedded in all my mods
